version: "3"
services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn manage:app --host 0.0.0.0'
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - '8000:8000'
  db:
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    image: postgres:14.3

volumes:
  postgres_volume: